# CONSTANTS
S_RIGHT, S_LEFT, S_UP, S_DOWN = 0, 1, 2, 3
XSIZE, YSIZE = 14, 14
NFOOD = 1

#VARIABLES
MAX_HEIGHT = 17
PARSIMONY_SIZE = 1.3
TOURNAMENT_FITNESS_SIZE = 7
CX_ONEPOINT_MAX_SIZE = 3
CROSS_PROB = 0.8
MUT_PROB = 0.2
ITERATIONS = 30
INDIVIDUAL_ITER = 4
HOF_SIZE = 2
POPULATION_SIZE = 350
FIT_FUNC = "steps"
FIT_TYPE = "average"